version: "3.8"

services:
  postgres:
    image: postgres:13.3

    environment:
      POSTGRES_DB: "playlist-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

    volumes:
      - ./schema/init.up.sql:/docker-entrypoint-initdb.d/init.up.sql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d playlist-db" ]
      interval: 5s
      timeout: 5s
      retries: 10

    ports:
      - "5432:5432"

  music-player-app:
    build: .

    environment:
      DBPORT: "5432"
      DBUSERNAME: "admin"
      DBPASSWORD: "admin"
      DBHOST: "postgres"
      DBNAME: "playlist-db"
      SSLMODE: "disable"
      PORT: "8000"

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"